### ISSUE TITLE
Where to find the ICS calendar file for meetings?

### ISSUE THREAD

**Issue by decentral1se** [dat-land/comm-comm#65]
Sorry if this is the wrong place for that but I'd like to request that there is an ICS calendar file published for meetings so that people can just hook it into their calendar infrastructure. It would help to catch the dates / times more easily and also deal with timezones etc.

**Comment by dpaez** [comment]
Hi @decentral1se! Yeah ICS calendar files are very helpful, @martinheidegger address this in the past so we have one. You can find it at the [comm-comm site](https://comm-comm.datproject.org/), right on the calendar icon.

ICS file: https://comm-comm.datproject.org/assets/dat-land_comm-comm.ics

Nevertheless, maybe we can give it more visibility since it's a bit lost. 🤔 Something like add it to the meetings issue? What do you think?

Hope it helps!

**Comment by martinheidegger** [comment]
We would welcome any PR that highlights the location of the calendar in a better way.
